package dynamo_spring_package.test;

import lombok.Data;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAtomicCounter;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbVersionAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

import java.time.Instant;

@DynamoDbBean
@Data
public class Test {
    private String id;
    private String title;
    private double price;
    private Long stockCount;
    private Instant createdDate;
    private Integer version;
    private Long counter;

    @DynamoDbPartitionKey
    public String getId() {
        return id;
    }

    @DynamoDbAttribute("title")
    public String getTitle() {
        return title;
    }

    @DynamoDbAttribute("price")
    public double getPrice() {
        return price;
    }

    @DynamoDbAttribute("stock_count")
    public Long getStockCount() {
        return stockCount;
    }

    @DynamoDbAttribute("created_date")
    @DynamoDbAutoGeneratedTimestampAttribute
    public Instant getCreatedDate() {
        return createdDate;
    }

    @DynamoDbAttribute("version")
    @DynamoDbVersionAttribute
    public Integer getVersion() {
        return version;
    }

    @DynamoDbAttribute("counter")
    @DynamoDbAtomicCounter
    public Long getCounter() {
        return counter;
    }
}
