package dynamo_spring_package.config;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClientExtension;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AtomicCounterExtension;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.enhanced.dynamodb.extensions.VersionedRecordExtension;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;

@Configuration
public class DynamoDbConfiguration {

    @Value("${aws.dynamodb.accessKey}")
    private String accessKey;

    @Value("${aws.dynamodb.secretKey}")
    private String secretKey;

    @Bean
    public DynamoDbClient dynamoDbClient(){
        return DynamoDbClient.builder().region(Region.AP_NORTHEAST_2).credentialsProvider(StaticCredentialsProvider.create(
                AwsBasicCredentials.create(accessKey, secretKey)
        )).build();
    }

    @Bean
    public DynamoDbEnhancedClient dynamoDbEnhancedClient(DynamoDbClient dynamoDbClient){
        DynamoDbEnhancedClientExtension versionedRecordExtension = VersionedRecordExtension.builder().build();
        DynamoDbEnhancedClientExtension autoGeneratedTimestampRecordExtension = AutoGeneratedTimestampRecordExtension.builder().build();
        DynamoDbEnhancedClientExtension atomicCounterExtension = AtomicCounterExtension.builder().build();
        return DynamoDbEnhancedClient.builder()
                        .dynamoDbClient(dynamoDbClient)
                        .extensions(versionedRecordExtension, autoGeneratedTimestampRecordExtension, atomicCounterExtension)
                        .build();
    }

}