package dynamo_spring_package.reoccuringPayments;

import lombok.Data;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.*;

import java.time.Instant;
import java.util.Map;

@DynamoDbBean
@Data
public class ReoccuringPayments {
    private String PK;
    private String SK;
    private Instant createdDate;
    private String email;
    private String lastPaymentDate;
    private String lastReminderDate;
    private String nextPaymentDate;
    private String nextReminderDate;
    private String paymentAmount;
    private String paymentDay;
    private Map<String, String> paymentDetails;
    private String processedAmount;
    private String processedDate;
    private String sku;
    private Long ttl;

    @DynamoDbPartitionKey
    public String getPK() {
        return PK;
    }

    @DynamoDbSortKey
    public String getSK() {
        return SK;
    }

    @DynamoDbAttribute("CreatedDate")
    @DynamoDbAutoGeneratedTimestampAttribute
    public Instant getCreatedDate() {
        return createdDate;
    }

    @DynamoDbAttribute("Email")
    public String getEmail() {
        return email;
    }

    @DynamoDbAttribute("LastPaymentDate")
    @DynamoDbSecondarySortKey(indexNames = "GSI-2")
    public String getLastPaymentDate() {
        return lastPaymentDate;
    }

    @DynamoDbAttribute("LastReminderDate")
    @DynamoDbSecondarySortKey(indexNames = "GSI-1")
    public String getLastReminderDate() {
        return lastReminderDate;
    }

    @DynamoDbAttribute("NextPaymentDate")
    @DynamoDbSecondaryPartitionKey(indexNames = "GSI-2")
    public String getNextPaymentDate() {
        return nextPaymentDate;
    }

    @DynamoDbAttribute("NextReminderDate")
    @DynamoDbSecondaryPartitionKey(indexNames = "GSI-1")
    public String getNextReminderDate() {
        return nextReminderDate;
    }

    @DynamoDbAttribute("PaymentAmount")
    public String getPaymentAmount() {
        return paymentAmount;
    }

    @DynamoDbAttribute("PaymentDay")
    public String getPaymentDay() {
        return paymentDay;
    }

    @DynamoDbAttribute("PaymentDetails")
    public Map<String, String> getPaymentDetails() {
        return paymentDetails;
    }

    @DynamoDbAttribute("ProcessedAmount")
    public String getProcessedAmount() {
        return processedAmount;
    }
    
    @DynamoDbAttribute("ProcessedDate")
    public String getProcessedDate() {
        return processedDate;
    }

    @DynamoDbAttribute("SKU")
    public String getSku() {
        return sku;
    }

    @DynamoDbAttribute("TTL")
    public Long getTtl() {
        return ttl;
    }
}
